Areas/Management/Controllers/LanguagesController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Portfolio.Areas.Management.Models;
using Portfolio.CustomAuthorization;
using Portfolio.Data.Entities;
using Portfolio.Data.UnitOfWork;

namespace Portfolio.Areas.Management.Controllers
{
    [Area("Management")]
    [CustomAuthorization]
    public class LanguagesController : BaseController<LanguagesController>
    {

        public LanguagesController(IUnitOfWork unitOfWork, IMapper mapper, IConfiguration configuration) : base(unitOfWork, mapper, configuration)
        {
        }

        public async Task<IActionResult> IndexAsync()
        {
            var languages = await _unitOfWork.LanguageRepository.GetAsync(includeProperties: new List<string>() { "Image" });
            var languageViewModels = _mapper.Map<List<LanguageViewModel>>(languages);
            languageViewModels.Reverse();
            return View(languageViewModels);
        }

        [HttpPost]
        public async Task<IActionResult> CreateAsync([FromForm] CreateLanguageViewModel languageViewModel)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest();
            }
            Language language = _mapper.Map<Language>(languageViewModel);
            string uniqueImageName = SaveImageAndGetTheImageName(languageViewModel.ImageFile);
            Image serviceImage = new Image()
            {
                Name = uniqueImageName,
                Title = language.Title,
                Alt = language.Title + " image"
            };
            language.Image = serviceImage;
            await _unitOfWork.LanguageRepository.AddAsync(language);
            await _unitOfWork.SaveAsync();

            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> EditAsync([FromForm] EditLanguageViewModel languageViewModel)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest();
            }
            Language language = _mapper.Map<Language>(languageViewModel);

            if (languageViewModel.ImageFile != null)
            {
                var image = await _unitOfWork.ImageRepository.GetByIdAsync(languageViewModel.ImageId);
                DeleteImage(image.Name);
                await _unitOfWork.ImageRepository.DeleteAsync(languageViewModel.ImageId);

                string uniqueImageName = SaveImageAndGetTheImageName(languageViewModel.ImageFile);
                Image languageImage = new Image()
                {
                    Name = uniqueImageName,
                    Title = language.Title,
                    Alt = language.Title + " image"
                };
                language.Image = languageImage;
                await _unitOfWork.ImageRepository.AddAsync(languageImage);
            }
            _unitOfWork.LanguageRepository.Update(language);
            await _unitOfWork.SaveAsync();

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> DeleteAsync(int id)
        {
            var language = await _unitOfWork.LanguageRepository.GetFirstByFilter(s => s.Id == id, includeProperties: new List<string>() { "Image" });
            DeleteImage(language.Image.Name);
            _unitOfWork.LanguageRepository.Delete(language);
            await _unitOfWork.SaveAsync();

            return RedirectToAction("Index");
        }
    }
}

Areas/Management/Controllers/ProjectsController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Portfolio.Areas.Management.Models;
using Portfolio.CustomAuthorization;
using Portfolio.Data.Entities;
using Portfolio.Data.UnitOfWork;

namespace Portfolio.Areas.Management.Controllers
{
    [Area("Management")]
    [CustomAuthorization]
    public class ProjectsController : BaseController<ProjectsController>
    {

        public ProjectsController(IUnitOfWork unitOfWork, IMapper mapper) : base(unitOfWork, mapper)
        {
        }

        public async Task<IActionResult> IndexAsync()
        {
            var projects = await _unitOfWork.ProjectRepository.GetAsync(includeProperties: new List<string>() { "Image" });
            var projectViewModels = _mapper.Map<List<ProjectViewModel>>(projects);
            projectViewModels.Reverse();
            return View(projectViewModels);
        }

        [HttpPost]
        public async Task<IActionResult> CreateAsync([FromForm] CreateProjectViewModel projectViewModel)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest();
            }
            Project project = _mapper.Map<Project>(projectViewModel);
            string uniqueImageName = SaveImageAndGetTheImageName(projectViewModel.ImageFile);
            Image projectImage = new Image()
            {
                Name = uniqueImageName,
                Title = project.Title,
                Alt = project.Title + " image"
            };
            project.Image = projectImage;
            await _unitOfWork.ProjectRepository.AddAsync(project);
            await _unitOfWork.SaveAsync();
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> EditAsync([FromForm] EditProjectViewModel projectViewModel)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest();
            }
            Project project = _mapper.Map<Project>(projectViewModel);

            if (projectViewModel.ImageFile != null)
            {
                var image = await _unitOfWork.ImageRepository.GetByIdAsync(projectViewModel.ImageId);
                DeleteImage(image.Name);
                _unitOfWork.ImageRepository.Delete(image);
                string uniqueImageName = SaveImageAndGetTheImageName(projectViewModel.ImageFile);
                Image projectImage = new Image()
                {
                    Name = uniqueImageName,
                    Title = project.Title,
                    Alt = project.Title + " image"
                };
                project.Image = projectImage;
            }
            _unitOfWork.ProjectRepository.Update(project);
            await _unitOfWork.SaveAsync();

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> DeleteAsync(int id)
        {
            var project = await _unitOfWork.ProjectRepository.GetFirstByFilter(s => s.Id == id, includeProperties: new List<string>() { "Image" });
            DeleteImage(project.Image.Name);
            _unitOfWork.ProjectRepository.Delete(project);
            await _unitOfWork.SaveAsync();

            return RedirectToAction("Index");
        }
    }
}

Areas/Management/Controllers/ServicesController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Portfolio.Areas.Management.Models;
using Portfolio.CustomAuthorization;
using Portfolio.Data.Entities;
using Portfolio.Data.UnitOfWork;

namespace Portfolio.Areas.Management.Controllers
{
    [Area("Management")]
    [CustomAuthorization]
    public class ServicesController : BaseController<ServicesController>
    {

        public ServicesController(IUnitOfWork unitOfWork, IMapper mapper) : base(unitOfWork, mapper)
        {
        }

        public async Task<IActionResult> IndexAsync()
        {

            var services = await _unitOfWork.ServiceRepository.GetAsync(includeProperties: new List<string>() { "Image" });
            var serviceViewModels = _mapper.Map<List<ServiceViewModel>>(services);
            serviceViewModels.Reverse();
            return View(serviceViewModels);
        }

        [HttpPost]
        public async Task<IActionResult> CreateAsync([FromForm] CreateServiceViewModel createServiceViewModel)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest();
            }
            Service service = _mapper.Map<Service>(createServiceViewModel);
            string uniqueImageName = SaveImageAndGetTheImageName(createServiceViewModel.ImageFile);
            Image serviceImage = new Image()
            {
                Name = uniqueImageName,
                Title = service.Title,
                Alt = service.Title + " image"
            };
            service.Image = serviceImage;
            await _unitOfWork.ServiceRepository.AddAsync(service);
            await _unitOfWork.SaveAsync();

            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> EditAsync([FromForm] EditServiceViewModel editServiceViewModel)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest();
            }
            Service service = _mapper.Map<Service>(editServiceViewModel);

            if (editServiceViewModel.ImageFile != null)
            {
                var image = await _unitOfWork.ImageRepository.GetByIdAsync(editServiceViewModel.ImageId);
                DeleteImage(image.Name);
                _unitOfWork.ImageRepository.Delete(image);
                string uniqueImageName = SaveImageAndGetTheImageName(editServiceViewModel.ImageFile);
                Image serviceImage = new Image()
                {
                    Name = uniqueImageName,
                    Title = service.Title,
                    Alt = service.Title + " image"
                };
                service.Image = serviceImage;
            }
            _unitOfWork.ServiceRepository.Update(service);
            await _unitOfWork.SaveAsync();

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> DeleteAsync(int id)
        {
            var service = await _unitOfWork.ServiceRepository.GetFirstByFilter(s => s.Id == id, includeProperties: new List<string>() { "Image" });
            DeleteImage(service.Image.Name);
            _unitOfWork.ServiceRepository.Delete(service);
            await _unitOfWork.SaveAsync();

            return RedirectToAction("Index");
        }

    }
}

Areas/Management/Controllers/TechnicalSkillsController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Portfolio.Areas.Management.Models;
using Portfolio.CustomAuthorization;
using Portfolio.Data.Entities;
using Portfolio.Data.UnitOfWork;

namespace Portfolio.Areas.Management.Controllers
{
    [Area("Management")]
    [CustomAuthorization]
    public class TechnicalSkillsController : BaseController<TechnicalSkillsController>
    {

        public TechnicalSkillsController(IUnitOfWork unitOfWork, IMapper mapper) : base(unitOfWork, mapper)
        {
        }

        public async Task<IActionResult> IndexAsync()
        {
            var technicalSkills = await _unitOfWork.TechnicalSkillRepository.GetAsync();
            var technicalSkillViewModels = _mapper.Map<List<TechnicalSkillViewModel>>(technicalSkills);
            technicalSkillViewModels.Reverse();
            return View(technicalSkillViewModels);
        }

        [HttpPost]
        public async Task<IActionResult> CreateAsync([FromForm] TechnicalSkillViewModel technicalSkillViewModel)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest();
            }
            TechnicalSkill technicalSkill = _mapper.Map<TechnicalSkill>(technicalSkillViewModel);
            await _unitOfWork.TechnicalSkillRepository.AddAsync(technicalSkill);
            await _unitOfWork.SaveAsync();
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> EditAsync([FromForm] TechnicalSkillViewModel technicalSkillViewModel)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest();
            }
            TechnicalSkill technicalSkill = _mapper.Map<TechnicalSkill>(technicalSkillViewModel);
            _unitOfWork.TechnicalSkillRepository.Update(technicalSkill);
            await _unitOfWork.SaveAsync();
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> DeleteAsync(int id)
        {
            var technicalSkill = await _unitOfWork.TechnicalSkillRepository.GetFirstByFilter(t => t.Id == id);
            _unitOfWork.TechnicalSkillRepository.Delete(technicalSkill);
            await _unitOfWork.SaveAsync();
            return RedirectToAction("Index");
        }

    }
}

Areas/Management/Views/Shared/_ImagePartial.cshtml
@model Portfolio.Areas.Management.Models.ImageViewModel
@{
    ViewBag.ImagesFolderAddress = "/images/";
}
<img id="@Model.HtmlId" class="@Model.HtmlClass" width="@Model.Width" height="@Model.Height" src="@ViewBag.ImagesFolderAddress@Model.Name" alt="@Model.Alt" title="@Model.Title">

Areas/Management/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en" dir="ltr">

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <link rel="icon" href="@ViewBag.ImagesFolderAddress/sitelogo.svg">
  <link rel="icon" href="~/images/logo.jpg">
  <title>@ViewData["Title"]</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.min.css" />
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css" />
  <script src="https://cdn.tailwindcss.com"></script>
  <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
  <link rel="stylesheet" href="~/css/customStyles.css" asp-append-version="true" />
  @RenderSection("Style", required: false)
  <style>
    a[active-navbar-item] {
      background-color: yellow;
    }
  </style>
</head>

<body class="text-blueGray-700 antialiased">
  <noscript>You need to enable JavaScript to run this app.</noscript>
  <div id="root">

    <nav class=" md:rigth-0 md:block md:fixed md:top-0 md:bottom-0 md:overflow-y-auto md:flex-row md:flex-nowrap
      md:overflow-hidden shadow-xl bg-white flex flex-wrap items-center justify-between relative md:w-64 z-10 p-2">
      <div
        class="md:flex-col md:items-stretch md:min-h-full md:flex-nowrap px-0 flex flex-wrap items-center justify-between w-full mx-auto">
        <button
          class="cursor-pointer text-black opacity-50 md:hidden px-3 py-1 text-xl leading-none bg-transparent rounded border border-solid border-transparent"
          type="button" onclick="removeClassFromElement([['navbar','hidden']])">
          <i class="fas fa-bars"></i>
        </button>
        <partial name="_SiteLogoPartial" />

        <div id="navbar" class="w-full bg-white py-1  md:flex md:flex-col md:items-stretch md:opacity-100 
          md:relative md:shadow-none shadow absolute top-0 left-0 right-0 z-40 
          overflow-y-auto overflow-x-hidden h-auto items-center flex-1 rounded hidden">
          <div class="md:block md:flex-row md:flex-nowrap md:overflow-hidden bg-white flex flex-wrap items-center justify-between relative md:w-64 z-10 py-1 px-2">
            <div class="flex justify-start flex-wrap">
              <div class="w-6/12 flex">
                <button type="button"
                  class="cursor-pointer text-black opacity-50 md:hidden px-3 py-1 text-xl leading-none bg-transparent rounded border border-solid border-transparent"
                  onclick="addClassToElement([['navbar','hidden']])">
                  <i class="fas fa-times"></i>
                </button>
              </div>
            </div>
          </div>


          <!-- Divider -->
          <hr class="my-2 md:min-w-full" />

          <ul class="px-2 md:px-0 md:flex-col text-base md:min-w-full flex flex-col list-none">
            <li class="items-center">
              <a asp-area="Management" asp-controller="Services" asp-action="Index"
                class="hover:text-blue-500 py-3 font-bold block text-blueGray-700 hover:text-blueGray-500">
                Services
              </a>
            </li>

            <li class="items-center">
              <a asp-area="Management" asp-controller="Projects" asp-action="Index"
                class="hover:text-blue-500 py-3 font-bold block text-blueGray-700 hover:text-blueGray-500">
                Projects
              </a>
            </li>

            <li class="items-center">
              <a asp-area="Management" asp-controller="Languages" asp-action="Index"
                class="hover:text-blue-500 py-3 font-bold block text-blueGray-700 hover:text-blueGray-500">
                Languages
              </a>
            </li>

            <li class="items-center">
              <a asp-area="Management" asp-controller="TechnicalSkills" asp-action="Index"
                class="hover:text-blue-500 py-3 font-bold block text-blueGray-700 hover:text-blueGray-500">
                Technical Skills
              </a>
            </li>

            <li class="items-center">
              <a asp-area="Management" asp-controller="Auth" asp-action="Logout"
                class="hover:text-blue-500 py-3 font-bold block text-blueGray-700 hover:text-blueGray-500">
                Logout
              </a>
            </li>

          </ul>
        </div>
      </div>
    </nav>
    <div class="relative md:ml-64 ">
      <nav
        class="hidden w-full md:flex z-10 bg-transparent flex-row flex-nowrap justify-start flex items-center p-4">
        <div class="w-full justify-between mx-autp items-center flex flex-nowrap flex-wrap px-4">
          <span class="text-xl font-semibold">
            @ViewData["Title"]
          </span>
        </div>
      </nav>

      <div class="relative">
        @RenderBody()
      </div>
    </div>
  </div>

  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

  <script
    src="https://cdnjs.cloudflare.com/ajax/libs/jquery-ajax-unobtrusive/3.2.6/jquery.unobtrusive-ajax.min.js"></script>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.3/jquery.validate.js"></script>
  <script
    src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.12/jquery.validate.unobtrusive.js"></script>

  <script src="~/js/site.js" asp-append-version="true"></script>
  <script src="~/js/scripts.js" asp-append-version="true"></script>

</body>

</html>

Areas/Management/Views/Shared/_SiteLogoPartial.cshtml
<a asp-area="" asp-controller="" asp-action=""
  class="cursor-pointer inline-flex items-center justify-center"
>
   @{
        var image = new ImageViewModel()
            {
                Name = "logo.jpg",
                HtmlClass = "h-10 w-10 rounded-md"
            };
    }
  <partial name="_ImagePartial" model="image" />
  <h3 class="ml-2">Portfolio</h3>
</a>